# -*- coding: utf-8 -*-
"""Udemy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yuxPxhmAEXtslbiH3HXIs7Q_8segoZjt

Coding Quiz (1)
Write a Python program to convert these numbers into string then into float types: 10,20,30,40,50,60,70,80,90,100
"""

numbers = range(1,10)
for number in numbers:
    x = number*10
    print(x)
y=str(x)
print(y)
z= float(x)
print(z)

"""Coding Quiz (2)
Write a program in python that take two string to complete and form a message that we can understand?
msg =  "python is ________  & _______  language and suitable for data analysis"
"""

a = input ("Enter your idea:")
b = input ("Enter your idea:")
msg="python is" + a + "&" + b + "language and suitable for data analysis"
print(msg)

"""Coding Quiz (3)

Write  a program in python to declare the name of this programming language and calculate length of this name.
"""

a = input ("Enter your idea:")
b = input ("Enter your idea:")
msg="python is" + a + "&" + b + "language and suitable for data analysis"
print(msg)
print(len(msg))
print(len(a))
print(len(a[0:4]))
print(a[0:4])

"""Coding Quiz (4)

Write a program in python to declare a message for an instructing sign in public place and get the length of that message and count of message letters:
"""

message = "my favorite language is persian"
print(len(message))

message.count('a')

message.count('v',3) #in order to count from index 3 to end

message.count('g',0,25) #in order to count from index 0 to 30

"""Coding Quiz (5)

Write a program in python to count to count the vowels in the following string:
" are you working as a Python programmer ?"
"""

c = " are you working as a Python programmer ?"
c.count('a')

c.count('e')

c.count('o')

c.count('i')

c.count('u')

"""Coding Quiz (6)

Write  a program in python to declare four messages to the community of technology that the Python programming language is wonderful but describe python with  a different description in each message you will write , so with one message withe one python description then answer the following questions:
How long each message you write is?
what is the count of a specific letter in each message you will write?
are the codes you write end with "l"?
are the codes you write start with "T"?
"""

x = "I love python language"
O = "Python is a powerful language"
P = "the python language is useful for computer vision"
U = "python is elegant"
print(len(x))
print(len(O))
print(len(P))
print(len(U))
x.count("I")
O.count("p")
P.count("o")
U.count("e")
x.endswith("e")



P.endswith("P")

U.endswith("m")

"""string.find(value, start, end)

Coding Quiz (7)

Write a program in python contain string "Don't turn left!" and then check if this string contain ( '!') and('m')
"""

T = "Don't turn left "
T.find('i')
T.find('m')

T.index('t')

"""Coding Quiz (8)

write a program in python contain  a string message for an electrical instructional sign in the street warning the cars drivers that they don't to turn left.
then check the string case.
then make it in upper case  in one code
finally make it in lower case in a second code.
Head to the next Hy
"""

w="Don't turn left"
w.isupper()

w.islower()

w.upper()

w.lower()

"""Coding Quiz (9)

write a program in python to declare that The coding is fun, then replace the word 'fun' with  the 'awesome' and then remove the word ' The' :
"""

Q="The coding is fun!"
Q.replace('fun','awesome')

Q.strip('The')
#strip for remove char

"""Coding Quiz (10)

Run the following lines of coding to see the result:
string = 'python is powerful language'
string.capitalize()
string = '1st programming language'
string.capitalize()
string = 'pYTHON IS POWERFUL PROGRAMMING LANGUAGE'
string.swapcase()
string = 'Python the powerful programming language'
string.title()
"""

string = 'python is powerful language'
string.capitalize()

string = '1st programming language'
string.capitalize()

string = 'pYTHON IS POWERFUL PROGRAMMING LANGUAGE'
string.swapcase()

string = 'Python the powerful programming language'
string.title()

"""\ newline ignored"""

print("line1 \
line2 \
line3")

"""\\Backslash (\)"""

print("\\")

"""\'Single quote (')"""

print('\'')

"""\"Double quote (")"""

print("\"")

"""\a \b"""

print("Hello \b World!")

print("Hello \f World!")

"""\n newline"""

print("Hello \n World!")

"""\r new line"""

print("Hello \r World!")

"""\t horizontal tab"""

print("Hello \t World!")

"""\v vertical tab"""

print("Hello \v World!")